# Generated by Django 5.0.7 on 2024-08-07 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logp', '0002_lregister_delete_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lregister',
            new_name='Register',
        ),
    ]
